language: cpp
notifications:
    email: false
sudo: required
dist: trusty
compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - export NG_CLI_ANALYTICS=ci

script:
  - gcc -v
  - cd src
  - make
  - sudo ./test

